#include "../includes/erros.hpp"

ServerErrorHandler::ServerErrorHandler()
{
	initializeErrorMessages();
}

void ServerErrorHandler::initializeErrorMessages()
{
	errorMessages[400] = "Bad Request";
	errorMessages[401] = "Unauthorized";
	errorMessages[403] = "Forbidden";
	errorMessages[404] = "Not Found";
	errorMessages[405] = "Method Not Allowed";
	errorMessages[406] = "Not Acceptable";
	errorMessages[407] = "Proxy Authentication Required";
	errorMessages[408] = "Request Timeout";
	errorMessages[409] = "Conflict";
	errorMessages[410] = "Gone";
	errorMessages[411] = "Length Required";
	errorMessages[412] = "Precondition Failed";
	errorMessages[413] = "Payload Too Large";
	errorMessages[414] = "URI Too Long";
	errorMessages[415] = "Unsupported Media Type";
	errorMessages[416] = "Range Not Satisfiable";
	errorMessages[417] = "Expectation Failed";
	errorMessages[418] = "I'm a teapot";
	errorMessages[421] = "Misdirected Request";
	errorMessages[422] = "Unprocessable Entity";
	errorMessages[423] = "Locked";
	errorMessages[424] = "Failed Dependency";
	errorMessages[426] = "Upgrade Required";
	errorMessages[428] = "Precondition Required";
	errorMessages[429] = "Too Many Requests";
	errorMessages[431] = "Request Header Fields Too Large";
	errorMessages[451] = "Unavailable For Legal Reasons";
	errorMessages[500] = "Internal Server Error";
	errorMessages[501] = "Not Implemented";
	errorMessages[502] = "Bad Gateway";
	errorMessages[503] = "Service Unavailable";
	errorMessages[504] = "Gateway Timeout";
	errorMessages[505] = "HTTP Version Not Supported";
	errorMessages[506] = "Variant Also Negotiates";
	errorMessages[507] = "Insufficient Storage";
	errorMessages[508] = "Loop Detected";
	errorMessages[510] = "Not Extended";
	errorMessages[511] = "Network Authentication Required";
}

std::string ServerErrorHandler::generateErrorPage(int errorCode, const std::string& errorMessage)
{
	std::ostringstream html;
	html << "<!DOCTYPE html>\n"
		 << "<html lang=\"en\">\n"
		 << "<head>\n"
		 << "\t<meta charset=\"UTF-8\">\n"
		 << "\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
		 << "\t<style>\n"
		 << "\t\tbody { font-family: Arial, sans-serif; text-align: center; padding: 50px; background-color: #ADD8E6; }\n"
		 << "\t\th1 { font-size: 50px; }\n"
		 << "\t\t.errorCode { color: red; }\n"
		 << "\t\tp { font-size: 20px; color: #333; }\n"
		 << "\t\t.error-container { max-width: 600px; margin: auto; }\n"
		 << "\t</style>\n"
		 << "\t<title>Error " << errorCode << "</title>\n"
		 << "</head>\n"
		 << "<body>\n"
		 << "\t<div class=\"error-container\">\n"
		 << "\t\t<h1 class=\"errorCode\">Error " << errorCode << "</h1>\n"
		 << "\t\t<p>" << errorMessage << "</p>\n"
		 << "\t\t<br>\n"
		 << "\t\t<button onclick=\"location.href='/'\">Home</button>\n"
		 << "\t</div>\n"
		 << "</body>\n"
		 << "</html>\n"
		 << "\n";
	return html.str();
}

std::string ServerErrorHandler::AgenerateErrorPage_2(std::string errorCodeStr)
{
    (void) errorCodeStr;
	std::ostringstream html;
	html << "<!DOCTYPE html>\n"
		 << "<html lang=\"en\">\n"
		 << "<head>\n"
		 << "\t<meta charset=\"UTF-8\">\n"
		 << "\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
		 << "\t<style>\n"
		 << "\t\tbody { font-family: Arial, sans-serif; text-align: center; padding: 50px; background-color: #ADD8E6; }\n"
		 << "\t\th1 { font-size: 50px; }\n"
		 << "\t\t.errorCode { color: red; }\n"
		 << "\t\tp { font-size: 20px; color: #333; }\n"
		 << "\t\t.error-container { max-width: 600px; margin: auto; }\n"
		 << "\t</style>\n"
		 << "\t<title>Error " << "Default Error Page" << "</title>\n"
		 << "</head>\n"
		 << "<body>\n"
		 << "\t<div class=\"error-container\">\n"
		 << "\t\t<h1 class=\"errorCode\">Error " << "xxx" << "</h1>\n"
		 << "\t\t<p>" << "Default Error Page for " << "xxx" << "</p>\n"
		 << "\t\t<br>\n"
		 << "\t\t<button onclick=\"location.href='/'\">Home</button>\n"
		 << "\t</div>\n"
		 << "</body>\n"
		 << "</html>\n"
		 << "\n";
	return html.str();
}

std::string ServerErrorHandler::AgenerateErrorPage_3(std::string errorCodeStr)
{
    (void)errorCodeStr;
	std::ostringstream html;
	html << "<!DOCTYPE html>\n"
		 << "<html lang=\"en\">\n"
		 << "<head>\n"
		 << "\t<meta charset=\"UTF-8\">\n"
		 << "\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
		 << "\t<style>\n"
		 << "\t\tbody { font-family: Arial, sans-serif; text-align: center; padding: 50px; background-color: #ADD8E6; }\n"
		 << "\t\th1 { font-size: 50px; }\n"
		 << "\t\t.errorCode { color: red; }\n"
		 << "\t\tp { font-size: 20px; color: #333; }\n"
		 << "\t\t.error-container { max-width: 600px; margin: auto; }\n"
		 << "\t</style>\n"
		 << "\t<title>Error " << "Default Error Page" << "</title>\n"
		 << "</head>\n"
		 << "<body>\n"
		 << "\t<div class=\"error-container\">\n"
		 << "\t\t<h1 class=\"errorCode\">Error " << "500" << "</h1>\n"
		 << "\t\t<p>" << "Default Error Page for " << "500" << "</p>\n"
		 << "\t\t<br>\n"
		 << "\t\t<button onclick=\"location.href='/'\">Home</button>\n"
		 << "\t</div>\n"
		 << "</body>\n"
		 << "</html>\n"
		 << "\n";
	return html.str();
}

// Gera uma página de erro HTML baseada no código de erro
std::string ServerErrorHandler::BgenerateErrorPage_2(std::string errorCodeStr)
{
    std::string aaa = errorCodeStr;

    if (errorCodeStr.substr(0, 3).find('x') != std::string::npos)
    {
        if (aaa[0] == '4')
        {
            aaa = "4xx";
            errorCodeStr = aaa;
            return AgenerateErrorPage_2(errorCodeStr);
        }
        else if (aaa[0] == '5')
        {
            aaa = "5xx";
            errorCodeStr = aaa;
            return AgenerateErrorPage_3(aaa);
        }
        else
        {
            aaa = "xxx";
            errorCodeStr = aaa;
            return AgenerateErrorPage_2(errorCodeStr);
        }
    }
    else
        return generateErrorPage(500, "Internal Server Error");
}

std::string ServerErrorHandler::generateErrorPage(int errorCode)
{
	std::map<int, std::string>::iterator it = errorMessages.find(errorCode);
	if (it != errorMessages.end())
		return generateErrorPage(errorCode, it->second);
	else
		return generateErrorPage(500, "Internal Server Error");
}

std::string ServerErrorHandler::getErrorMessage(int errorCode)
{
	std::map<int, std::string>::iterator it = errorMessages.find(errorCode);
	if (it != errorMessages.end())
		return it->second;
	else
		return "Unknown Error";
}

std::string ServerErrorHandler::generateIndex(const std::string& name)
{
    std::ostringstream html;
    html << "<!DOCTYPE html>\n"
         << "<html lang=\"en\">\n"
         << "\t<head>\n"
         << "\t\t<meta charset=\"UTF-8\">\n"
         << "\t\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n"
         << "\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
         << "\t\t<title>Webserver Home</title>\n"
         << "\t\t<style>\n"
         << "\t\t\tbody {\n"
         << "\t\t\t\tfont-family: Arial, sans-serif;\n"
         << "\t\t\t\tdisplay: flex;\n"
         << "\t\t\t\tjustify-content: center;\n"
         << "\t\t\t\talign-items: center;\n"
         << "\t\t\t\theight: 70vh;\n"
         << "\t\t\t\tmargin: 0;\n"
         << "\t\t\t\tbackground-color: #01012b;\n"
         << "\t\t\t}\n"
         << "\t\t\t@keyframes pulse {\n"
         << "\t\t\t\t0% { transform: scale(1); }\n"
         << "\t\t\t\t50% { transform: scale(1.1); }\n"
         << "\t\t\t\t100% { transform: scale(1); }\n"
         << "\t\t\t}\n"
         << "\t\t\th1 {\n"
         << "\t\t\t\tfont-family: \"Arial\", monospace;\n"
         << "\t\t\t\tfont-size: 4.5em;\n"
         << "\t\t\t\tfont-weight: 900;\n"
         << "\t\t\t\tanimation: pulse 3s infinite;\n"
         << "\t\t\t}\n"
         << "\t\t\t.container {\n"
         << "\t\t\t\ttext-align: center;\n"
         << "\t\t\t\tmax-width: 850px;\n"
         << "\t\t\t\twidth: 100%;\n"
         << "\t\t\t\tbackground-color: #94bbd0;\n"
         << "\t\t\t\tpadding: 20px;\n"
         << "\t\t\t\tborder-radius: 10px;\n"
         << "\t\t\t\tbox-shadow: 0px 0px 10px 0px rgba(0, 0, 0, 0.1);\n"
         << "\t\t\t}\n"
         << "\t\t\t.buttons {\n"
         << "\t\t\t\tfont-size: 20px;\n"
         << "\t\t\t\tpadding: 10px 20px;\n"
         << "\t\t\t\tborder: none;\n"
         << "\t\t\t\tborder-radius: 8px;\n"
         << "\t\t\t\tcursor: pointer;\n"
         << "\t\t\t\tmargin-bottom: 20px;\n"
         << "\t\t\t\tmargin-left: 10px;\n"
         << "\t\t\t\tmargin-top: 5px;\n"
         << "\t\t\t}\n"
         << "\t\t\t.credits_1 {\n"
         << "\t\t\t\ttext-align: center;\n"
         << "\t\t\t\tpadding: 15px;\n"
         << "\t\t\t\tbackground-color: #5f94c9;\n"
         << "\t\t\t\tmargin-top: 20px;\n"
         << "\t\t\t\tborder-radius: 10px;\n"
         << "\t\t\t}\n"
         << "\t\t\t.credits_2 {\n"
         << "\t\t\t\tmax-width: 850px;\n"
         << "\t\t\t\tmargin: auto;\n"
         << "\t\t\t}\n"
         << "\t\t\ta[href*=\"https://profile.intra.42.fr\"] {\n"
         << "\t\t\t\tcolor: rgb(7, 7, 114);\n"
         << "\t\t\t}\n"
         << "\t\t\ta[href*=\"https://profile.intra.42.fr\"]:hover {\n"
         << "\t\t\t\tcolor: rgb(255, 255, 255);\n"
         << "\t\t\t}\n"
         << "\t\t\ta[href*=\"https://github.com\"] {\n"
         << "\t\t\t\tcolor: rgb(7, 7, 114);\n"
         << "\t\t\t}\n"
         << "\t\t\ta[href*=\"https://github.com\"]:hover {\n"
         << "\t\t\t\tcolor: rgb(255, 255, 255);\n"
         << "\t\t\t}\n"
         << "\t\t\t.glow-on-hover {\n"
         << "\t\t\t\tborder: none;\n"
         << "\t\t\t\toutline: none;\n"
         << "\t\t\t\tcolor: #fff;\n"
         << "\t\t\t\tcursor: pointer;\n"
         << "\t\t\t\tposition: relative;\n"
         << "\t\t\t\tz-index: 0;\n"
         << "\t\t\t\tborder-radius: 10px;\n"
         << "\t\t\t}\n"
         << "\t\t\t.glow-on-hover:before {\n"
         << "\t\t\t\tcontent: '';\n"
         << "\t\t\t\tbackground: linear-gradient(45deg, #ff0000, #ff0000);\n"
         << "\t\t\t\tposition: absolute;\n"
         << "\t\t\t\ttop: -2px;\n"
         << "\t\t\t\tleft:-2px;\n"
         << "\t\t\t\tbackground-size: 400%;\n"
         << "\t\t\t\tz-index: -1;\n"
         << "\t\t\t\tfilter: blur(5px);\n"
         << "\t\t\t\twidth: calc(100% + 5px);\n"
         << "\t\t\t\theight: calc(100% + 5px);\n"
         << "\t\t\t\tanimation: glowing 20s linear infinite;\n"
         << "\t\t\t\topacity: 0;\n"
         << "\t\t\t\ttransition: opacity .3s ease-in-out;\n"
         << "\t\t\t\tborder-radius: 10px;\n"
         << "\t\t\t}\n"
         << "\t\t\t.glow-on-hover:active {\n"
         << "\t\t\t\tcolor: #000000;\n"
         << "\t\t\t}\n"
         << "\t\t\t.glow-on-hover:active:after {\n"
         << "\t\t\t\tbackground: #72bae0;\n"
         << "\t\t\t}\n"
         << "\t\t\t.glow-on-hover:hover:before {\n"
         << "\t\t\t\topacity: 1;\n"
         << "\t\t\t}\n"
         << "\t\t\t.glow-on-hover:after {\n"
         << "\t\t\t\tz-index: -1;\n"
         << "\t\t\t\tcontent: '';\n"
         << "\t\t\t\tposition: absolute;\n"
         << "\t\t\t\twidth: 100%;\n"
         << "\t\t\t\theight: 100%;\n"
         << "\t\t\t\tbackground: #090345;\n"
         << "\t\t\t\tleft: 0;\n"
         << "\t\t\t\ttop: 0;\n"
         << "\t\t\t\tborder-radius: 10px;\n"
         << "\t\t\t}\n"
         << "\t\t</style>\n"
         << "\t\t<link rel=\"icon\" type=\"image/vnd.microsoft.icon\" href=\"favicon.ico\" >\n"
         << "\t</head>\n"
         << "\t<body>\n"
         << "\t\t<div class=\"container\">\n"
         << "\t\t\t<h1>WebServer</h1>\n"
         << "\t\t\t<a href=\"/" << name << "\"><button class=\"buttons glow-on-hover\"><b>Home</b></button></a>\n"
         << "\t\t\t<a href=\"/get.html\"><button class=\"buttons glow-on-hover\"><b>Get Page</b></button></a>\n"
         << "\t\t\t<a href=\"/post.html\"><button class=\"buttons glow-on-hover\"><b>Post Page</b></button></a>\n"
         << "\t\t\t<a href=\"/upload.html\"><button class=\"buttons glow-on-hover\"><b>Upload Page</b></button></a>\n"
         << "\t\t\t<a href=\"/delete.html\"><button class=\"buttons glow-on-hover\"><b>Delete Page</b></button></a>\n"
         << "\t\t\t<div class=\"credits_1\">\n"
         << "\t\t\t\t<h3>CREDITS</h3>\n"
         << "\t\t\t\t<table class=\"credits_2\">\n"
         << "\t\t\t\t\t<tr>\n"
         << "\t\t\t\t\t\t<td style=\"text-align: center;\"><b>Frederico Bajouco</b> [ </td>\n"
         << "\t\t\t\t\t\t<td style=\"text-align: center;\"><a href=\"https://profile.intra.42.fr/users/fde-carv\">Intra 42</a> | </td>\n"
         << "\t\t\t\t\t\t<td style=\"text-align: center;\"><a href=\"https://github.com/krammersf\">Github</a> ] </td>\n"
         << "\t\t\t\t\t\t<td style=\"text-align: center;\"><b>Filipa Borges</b> [ </td>\n"
         << "\t\t\t\t\t\t<td style=\"text-align: center;\"><a href=\"https://profile.intra.42.fr/users/firibeir\">Intra 42</a> | </td>\n"
         << "\t\t\t\t\t\t<td style=\"text-align: center;\"><a href=\"https://github.com/fiborges\">Github</a> ] </td>\n"
         << "\t\t\t\t\t\t<td style=\"text-align: center;\"><b>Bruno Soares</b> [ </td>\n"
         << "\t\t\t\t\t\t<td style=\"text-align: center;\"><a href=\"https://profile.intra.42.fr/users/brolivei\">Intra 42</a> | </td>\n"
         << "\t\t\t\t\t\t<td style=\"text-align: center;\"><a href=\"https://github.com/BrunoAlone\">Github</a> ] </td>\n"
         << "\t\t\t\t\t</tr>\n"
         << "\t\t\t\t</table>\n"
         << "\t\t\t</div>\n"
         << "\t\t</div>\n"
         << "\t</body>\n"
         << "</html>";
    return html.str();
}


std::string ServerErrorHandler::generateDelete()
{
    std::ostringstream html;
    html << "<!DOCTYPE html>\n"
         << "<html lang=\"en\">\n"
         << "\t<head>\n"
         << "\t\t<meta charset=\"UTF-8\">\n"
         << "\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
         << "\t\t<title>Delete a file from the upload directory</title>\n"
         << "\t\t<style>\n"
         << "\t\t\tbody {\n"
         << "\t\t\t\tfont-family: Arial, sans-serif;\n"
         << "\t\t\t\tdisplay: flex;\n"
         << "\t\t\t\tjustify-content: center;\n"
         << "\t\t\t\talign-items: center;\n"
         << "\t\t\t\theight: 70vh;\n"
         << "\t\t\t\tmargin: 0;\n"
         << "\t\t\t\tbackground-color: #01012b;\n"
         << "\t\t\t}\n"
         << "\t\t\th1 {\n"
         << "\t\t\t\tfont-family: \"Arial\", monospace;\n"
         << "\t\t\t\tfont-size: 2.5em;\n"
         << "\t\t\t\tfont-weight: 900;\n"
         << "\t\t\t}\n"
         << "\t\t\t.container {\n"
         << "\t\t\t\ttext-align: center;\n"
         << "\t\t\t\tmax-width: 850px;\n"
         << "\t\t\t\twidth: 100%;\n"
         << "\t\t\t\tbackground-color: #94bbd0;\n"
         << "\t\t\t\tpadding: 20px;\n"
         << "\t\t\t\tborder-radius: 10px;\n"
         << "\t\t\t\tbox-shadow: 0px 0px 10px 0px rgba(0, 0, 0, 0.1);\n"
         << "\t\t\t}\n"
         << "\t\t\t.buttons {\n"
         << "\t\t\t\tfont-size: 20px;\n"
         << "\t\t\t\tpadding: 10px 20px;\n"
         << "\t\t\t\tborder: none;\n"
         << "\t\t\t\tborder-radius: 8px;\n"
         << "\t\t\t\tcursor: pointer;\n"
         << "\t\t\t\tmargin-bottom: 20px;\n"
         << "\t\t\t\tmargin-left: 10px;\n"
         << "\t\t\t\tmargin-top: 5px;\n"
         << "\t\t\t}\n"
         << "\t\t\t.home-button {\n"
         << "\t\t\t\tdisplay: flex;\n"
         << "\t\t\t\tjustify-content: center;\n"
         << "\t\t\t\tmargin-bottom: 20px;\n"
         << "\t\t\t}\n"
         << "\t\t\t.file-message {\n"
         << "\t\t\t\tmargin-top: 10px;\n"
         << "\t\t\t\tmargin-bottom: 10px;\n"
         << "\t\t\t\tpadding-left: 4em;\n"
         << "\t\t\t\ttext-align: left;\n"
         << "\t\t\t}\n"
         << "\t\t\t.file-message strong {\n"
         << "\t\t\t\tfont-weight: bold;\n"
         << "\t\t\t\tcolor: rgb(255, 255, 255);\n"
         << "\t\t\t\tfont-size: 20px;\n"
         << "\t\t\t}\n"
         << "\t\t\t.file-name {\n"
         << "\t\t\t\tcolor: red;\n"
         << "\t\t\t}\n"
         << "\t\t\t.glow-on-hover {\n"
         << "\t\t\t\tborder: none;\n"
         << "\t\t\t\toutline: none;\n"
         << "\t\t\t\tcolor: #fff;\n"
         << "\t\t\t\tcursor: pointer;\n"
         << "\t\t\t\tposition: relative;\n"
         << "\t\t\t\tz-index: 0;\n"
         << "\t\t\t\tborder-radius: 10px;\n"
         << "\t\t\t}\n"
         << "\t\t\t.glow-on-hover:before {\n"
         << "\t\t\t\tcontent: '';\n"
         << "\t\t\t\tbackground: linear-gradient(45deg, #ff0000, #ff0000);\n"
         << "\t\t\t\tposition: absolute;\n"
         << "\t\t\t\ttop: -2px;\n"
         << "\t\t\t\tleft: -2px;\n"
         << "\t\t\t\tbackground-size: 400%;\n"
         << "\t\t\t\tz-index: -1;\n"
         << "\t\t\t\tfilter: blur(5px);\n"
         << "\t\t\t\twidth: calc(100% + 5px);\n"
         << "\t\t\t\theight: calc(100% + 5px);\n"
         << "\t\t\t\tanimation: glowing 20s linear infinite;\n"
         << "\t\t\t\topacity: 0;\n"
         << "\t\t\t\ttransition: opacity .3s ease-in-out;\n"
         << "\t\t\t\tborder-radius: 10px;\n"
         << "\t\t\t}\n"
         << "\t\t\t.glow-on-hover:active {\n"
         << "\t\t\t\tcolor: #000000;\n"
         << "\t\t\t}\n"
         << "\t\t\t.glow-on-hover:active:after {\n"
         << "\t\t\t\tbackground: #72bae0;\n"
         << "\t\t\t}\n"
         << "\t\t\t.glow-on-hover:hover:before {\n"
         << "\t\t\t\topacity: 1;\n"
         << "\t\t\t}\n"
         << "\t\t\t.glow-on-hover:after {\n"
         << "\t\t\t\tz-index: -1;\n"
         << "\t\t\t\tcontent: '';\n"
         << "\t\t\t\tposition: absolute;\n"
         << "\t\t\t\twidth: 100%;\n"
         << "\t\t\t\theight: 100%;\n"
         << "\t\t\t\tbackground: #090345;\n"
         << "\t\t\t\tleft: 0;\n"
         << "\t\t\t\ttop: 0;\n"
         << "\t\t\t\tborder-radius: 10px;\n"
         << "\t\t\t}\n"
         << "\t\t\t.delete-button {\n"
         << "\t\t\t\tbackground-color: #8d0000 !important;\n"
         << "\t\t\t\tcolor: #ffffff !important;\n"
         << "\t\t\t\tfont-weight: bold;\n"
         << "\t\t\t}\n"
         << "\t\t</style>\n"
         << "\t</head>\n"
         << "\t<body>\n"
         << "\t\t<div class=\"container\">\n"
         << "\t\t\t<h1>Delete a file from the upload directory</h1>\n"
         << "\t\t\t<div class=\"home-button\">\n"
         << "\t\t\t\t<a href=\"/\"><button class=\"buttons glow-on-hover\"><b>Home</b></button></a>\n"
         << "\t\t\t</div>\n"
         << "\t\t\t<div class=\"button-group\">\n"
         << "\t\t\t\t<input type=\"file\" name=\"file\" id=\"file\" class=\"buttons glow-on-hover\">\n"
         << "\t\t\t\t<button onclick=\"deleteFile()\" class=\"buttons glow-on-hover delete-button\">Delete</button>\n"
         << "\t\t\t</div>\n"
         << "\t\t\t<div class=\"file-message glow-on-hover\" id=\"file-message\"><strong>Selected file:</strong></div>\n"
         << "\t\t</div>\n"
         << "\t\t<script>\n"
         << "\t\t\tfunction deleteFile() {\n"
         << "\t\t\t\tvar input = document.getElementById('file');\n"
         << "\t\t\t\tvar file = input.files[0];\n"
         << "\t\t\t\tif (!file) {\n"
         << "\t\t\t\t\tdocument.getElementById('file-message').innerHTML = '<strong>Selected file:</strong>';\n"
         << "\t\t\t\t\talert('Please select a file to delete.');\n"
         << "\t\t\t\t\treturn;\n"
         << "\t\t\t\t}\n"
         << "\t\t\t\tvar xhr = new XMLHttpRequest();\n"
         << "\t\t\t\tvar url = '/cgi-bin/uploads/' + encodeURIComponent(file.name);\n"
         << "\t\t\t\txhr.open('DELETE', url, true);\n"
         << "\t\t\t\txhr.onreadystatechange = function () {\n"
         << "\t\t\t\t\tif (xhr.readyState == 4 && xhr.status == 200) {\n"
         << "\t\t\t\t\t\talert('File deleted successfully: ' + file.name);\n"
         << "\t\t\t\t\t} else if (xhr.readyState == 4) {\n"
         << "\t\t\t\t\t\talert('Error deleting file: ' + file.name);\n"
         << "\t\t\t\t\t}\n"
         << "\t\t\t\t};\n"
         << "\t\t\t\txhr.send();\n"
         << "\t\t\t\tdocument.getElementById('file-message').innerHTML = '<strong>Selected file: </strong> <span class=\"file-name\">' + file.name + '</span>';\n"
         << "\t\t\t\tinput.value = '';\n"
         << "\t\t\t}\n"
         << "\t\t</script>\n"
         << "\t</body>\n"
         << "</html>";
    return html.str();
}


std::string ServerErrorHandler::generateGet()
{
    std::ostringstream html;
    html << "<!DOCTYPE html>\n"
         << "<html lang=\"en\">\n"
         << "<head>\n"
         << "\t<meta charset=\"UTF-8\">\n"
         << "\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n"
         << "\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
         << "\t<title>Formulário POST</title>\n"
         << "\t<style>\n"
         << "\t\tbody {\n"
         << "\t\t\tfont-family: Arial, sans-serif;\n"
         << "\t\t\tdisplay: flex;\n"
         << "\t\t\tjustify-content: center;\n"
         << "\t\t\talign-items: center;\n"
         << "\t\t\theight: 70vh;\n"
         << "\t\t\tmargin: 0;\n"
         << "\t\t\tbackground-color: #01012b;\n"
         << "\t\t}\n"
         << "\t\t@keyframes pulse {\n"
         << "\t\t\t0% {\n"
         << "\t\t\t\ttransform: scale(1);\n"
         << "\t\t\t}\n"
         << "\t\t\t50% {\n"
         << "\t\t\t\ttransform: scale(1.1);\n"
         << "\t\t\t}\n"
         << "\t\t\t100% {\n"
         << "\t\t\t\ttransform: scale(1);\n"
         << "\t\t\t}\n"
         << "\t\t}\n"
         << "\t\th1 {\n"
         << "\t\t\tfont-family: \"Arial\", monospace;\n"
         << "\t\t\tfont-size: 2.5em;\n"
         << "\t\t\tfont-weight: 900;\n"
         << "\t\t}\n"
         << "\t\t.container {\n"
         << "\t\t\ttext-align: center;\n"
         << "\t\t\tmax-width: 850px;\n"
         << "\t\t\twidth: 100%;\n"
         << "\t\t\tbackground-color: #94bbd0;\n"
         << "\t\t\tpadding: 20px;\n"
         << "\t\t\tborder-radius: 10px;\n"
         << "\t\t\tbox-shadow: 0px 0px 10px 0px rgba(0, 0, 0, 0.1);\n"
         << "\t\t}\n"
         << "\t\t.buttons {\n"
         << "\t\t\tfont-size: 20px;\n"
         << "\t\t\tpadding: 10px 20px;\n"
         << "\t\t\tborder: none;\n"
         << "\t\t\tborder-radius: 8px;\n"
         << "\t\t\tcursor: pointer;\n"
         << "\t\t\tmargin-bottom: 20px;\n"
         << "\t\t\tmargin-left: 10px;\n"
         << "\t\t\tmargin-top: 5px;\n"
         << "\t\t}\n"
         << "\t\t.credits_1 {\n"
         << "\t\t\ttext-align: center;\n"
         << "\t\t\tpadding: 15px;\n"
         << "\t\t\tbackground-color: #5f94c9;\n"
         << "\t\t\tmargin-top: 20px;\n"
         << "\t\t\tborder-radius: 10px;\n"
         << "\t\t}\n"
         << "\t\t.credits_2 {\n"
         << "\t\t\tmax-width: 850px;\n"
         << "\t\t\tmargin: auto;\n"
         << "\t\t}\n"
         << "\t\ta[href*=\"https://profile.intra.42.fr\"] {\n"
         << "\t\t\tcolor: rgb(7, 7, 114);\n"
         << "\t\t}\n"
         << "\t\ta[href*=\"https://profile.intra.42.fr\"]:hover {\n"
         << "\t\t\tcolor: rgb(255, 255, 255);\n"
         << "\t\t}\n"
         << "\t\ta[href*=\"https://github.com\"] {\n"
         << "\t\t\tcolor: rgb(7, 7, 114);\n"
         << "\t\t}\n"
         << "\t\ta[href*=\"https://github.com\"]:hover {\n"
         << "\t\t\tcolor: rgb(255, 255, 255);\n"
         << "\t\t}\n"
         << "\t\t.glow-on-hover {\n"
         << "\t\t\tborder: none;\n"
         << "\t\t\toutline: none;\n"
         << "\t\t\tcolor: #fff;\n"
         << "\t\t\tcursor: pointer;\n"
         << "\t\t\tposition: relative;\n"
         << "\t\t\tz-index: 0;\n"
         << "\t\t\tborder-radius: 10px;\n"
         << "\t\t}\n"
         << "\t\t.glow-on-hover:before {\n"
         << "\t\t\tcontent: '';\n"
         << "\t\t\tbackground: linear-gradient(45deg, #ff0000, #ff0000);\n"
         << "\t\t\tposition: absolute;\n"
         << "\t\t\ttop: -2px;\n"
         << "\t\t\tleft:-2px;\n"
         << "\t\t\tbackground-size: 400%;\n"
         << "\t\t\tz-index: -1;\n"
         << "\t\t\tfilter: blur(5px);\n"
         << "\t\t\twidth: calc(100% + 5px);\n"
         << "\t\t\theight: calc(100% + 5px);\n"
         << "\t\t\tanimation: glowing 20s linear infinite;\n"
         << "\t\t\topacity: 0;\n"
         << "\t\t\ttransition: opacity .3s ease-in-out;\n"
         << "\t\t\tborder-radius: 10px;\n"
         << "\t\t}\n"
         << "\t\t.glow-on-hover:active {\n"
         << "\t\t\tcolor: #000000\n"
         << "\t\t}\n"
         << "\t\t.glow-on-hover:active:after {\n"
         << "\t\t\tbackground: #72bae0;\n"
         << "\t\t}\n"
         << "\t\t.glow-on-hover:hover:before {\n"
         << "\t\t\topacity: 1;\n"
         << "\t\t}\n"
         << "\t\t.glow-on-hover:after {\n"
         << "\t\t\tz-index: -1;\n"
         << "\t\t\tcontent: '';\n"
         << "\t\t\tposition: absolute;\n"
         << "\t\t\twidth: 100%;\n"
         << "\t\t\theight: 100%;\n"
         << "\t\t\tbackground: #090345;\n"
         << "\t\t\tleft: 0;\n"
         << "\t\t\ttop: 0;\n"
         << "\t\t\tborder-radius: 10px;\n"
         << "\t\t}\n"
         << "\t\t.upload-button {\n"
         << "\t\t\tbackground-color: #8d0000;\n"
         << "\t\t\tcolor: #ffffff;\n"
         << "\t\t\tfont-weight: bold\n"
         << "\t\t}\n"
         << "\t\t.large-bold {\n"
         << "\t\t\tfont-size: 2em;\n"
         << "\t\t\tfont-weight: bold;\n"
         << "\t\t}\n"
         << "\t\t.large-bold2 {\n"
         << "\t\t\tfont-size: 1.2em;\n"
         << "\t\t\tfont-weight: bold;\n"
         << "\t\t}\n"
         << "\t\t.large-bold3 {\n"
         << "\t\t\tfont-weight: bold;\n"
         << "\t\t\tdisplay: inline;\n"
         << "\t\t}\n"
         << "\t</style>\n"
         << "</head>\n"
         << "<body>\n"
         << "\t<div class=\"container\">\n"
         << "\t\t<h1>Get Page</h1>\n"
         << "\t\t<a href=\"/\"><button class=\"buttons glow-on-hover\"><b>Home</b></button></a>\n"
         << "\t\t<form action=\"http://localhost:8080\" method=\"post\"><br>\n"
         << "\t\t\t<div class=\"large-bold\">Webserv<br></div><br>\n"
         << "\t\t\t<div class=\"large-bold2\">This is when you finally understand why a URL startswith HTTP<br></div><br>\n"
         << "\t\t\t<div class=\"large-bold3\">Summary:</div>\n"
         << "\t\t\tThis project is about writing your own HTTP server.\n"
         << "\t\t\tYou will be able to test it with an actual browser.\n"
         << "\t\t\tHTTP is one of the most used protocols on the internet.\n"
         << "\t\t\tKnowing its arcane will be useful, even if you won’t be working on a website.\n"
         << "\t\t\tVersion: 21.2\n"
         << "\t\t</form>\n"
         << "\t</div>\n"
         << "</body>\n"
         << "</html>\n";
    return html.str();
}

std::string ServerErrorHandler::generatePost()
{
    std::ostringstream html;
    html << "<!DOCTYPE html>\n"
         << "<html lang=\"en\">\n"
         << "<head>\n"
         << "\t<meta charset=\"UTF-8\">\n"
         << "\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n"
         << "\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
         << "\t<title>Formulário POST</title>\n"
         << "\t<style>\n"
         << "\tbody {\n"
         << "\t\tfont-family: Arial, sans-serif;\n"
         << "\t\tdisplay: flex;\n"
         << "\t\tjustify-content: center;\n"
         << "\t\talign-items: center;\n"
         << "\t\theight: 70vh;\n"
         << "\t\tmargin: 0;\n"
         << "\t\tbackground-color: #01012b;\n"
         << "\t}\n"
         << "\t@keyframes pulse {\n"
         << "\t\t0% {\n"
         << "\t\t\ttransform: scale(1);\n"
         << "\t\t}\n"
         << "\t\t50% {\n"
         << "\t\t\ttransform: scale(1.1);\n"
         << "\t\t}\n"
         << "\t\t100% {\n"
         << "\t\t\ttransform: scale(1);\n"
         << "\t\t}\n"
         << "\t}\n"
         << "\th1 {\n"
         << "\t\tfont-family: \"Arial\", monospace;\n"
         << "\t\tfont-size: 2.5em;\n"
         << "\t\tfont-weight: 900;\n"
         << "\t}\n"
         << "\t.container {\n"
         << "\t\ttext-align: center;\n"
         << "\t\tmax-width: 850px;\n"
         << "\t\twidth: 100%;\n"
         << "\t\tbackground-color: #94bbd0;\n"
         << "\t\tpadding: 20px;\n"
         << "\t\tborder-radius: 10px;\n"
         << "\t\tbox-shadow: 0px 0px 10px 0px rgba(0, 0, 0, 0.1);\n"
         << "\t}\n"
         << "\t.buttons {\n"
         << "\t\tfont-size: 20px;\n"
         << "\t\tpadding: 10px 20px;\n"
         << "\t\tborder: none;\n"
         << "\t\tborder-radius: 8px;\n"
         << "\t\tcursor: pointer;\n"
         << "\t\tmargin-bottom: 20px;\n"
         << "\t\tmargin-left: 10px;\n"
         << "\t\tmargin-top: 5px;\n"
         << "\t}\n"
         << "\t.credits_1 {\n"
         << "\t\ttext-align: center;\n"
         << "\t\tpadding: 15px;\n"
         << "\t\tbackground-color: #5f94c9;\n"
         << "\t\tmargin-top: 20px;\n"
         << "\t\tborder-radius: 10px;\n"
         << "\t}\n"
         << "\t.credits_2 {\n"
         << "\t\tmax-width: 850px;\n"
         << "\t\tmargin: auto;\n"
         << "\t}\n"
         << "\ta[href*=\"https://profile.intra.42.fr\"] {\n"
         << "\t\tcolor: rgb(7, 7, 114);\n"
         << "\t}\n"
         << "\ta[href*=\"https://profile.intra.42.fr\"]:hover {\n"
         << "\t\tcolor: rgb(255, 255, 255);\n"
         << "\t}\n"
         << "\ta[href*=\"https://github.com\"] {\n"
         << "\t\tcolor: rgb(7, 7, 114);\n"
         << "\t}\n"
         << "\ta[href*=\"https://github.com\"]:hover {\n"
         << "\t\tcolor: rgb(255, 255, 255);\n"
         << "\t}\n"
         << "\t.glow-on-hover {\n"
         << "\t\tborder: none;\n"
         << "\t\toutline: none;\n"
         << "\t\tcolor: #fff;\n"
         << "\t\tposition: relative;\n"
         << "\t\tz-index: 0;\n"
         << "\t\tborder-radius: 10px;\n"
         << "\t}\n"
         << "\t.glow-on-hover:before {\n"
         << "\t\tcontent: '';\n"
         << "\t\tbackground: linear-gradient(45deg, #ff0000, #ff0000);\n"
         << "\t\tposition: absolute;\n"
         << "\t\ttop: -2px;\n"
         << "\t\tleft:-2px;\n"
         << "\t\tbackground-size: 400%;\n"
         << "\t\tz-index: -1;\n"
         << "\t\tfilter: blur(5px);\n"
         << "\t\twidth: calc(100% + 5px);\n"
         << "\t\theight: calc(100% + 5px);\n"
         << "\t\tanimation: glowing 20s linear infinite;\n"
         << "\t\topacity: 0;\n"
         << "\t\ttransition: opacity .3s ease-in-out;\n"
         << "\t\tborder-radius: 10px;\n"
         << "\t}\n"
         << "\t.glow-on-hover:active {\n"
         << "\t\tcolor: #000000\n"
         << "\t}\n"
         << "\t.glow-on-hover:active:after {\n"
         << "\t\tbackground: #72bae0;\n"
         << "\t}\n"
         << "\t.glow-on-hover:hover:before {\n"
         << "\t\topacity: 1;\n"
         << "\t}\n"
         << "\t.glow-on-hover:after {\n"
         << "\t\tz-index: -1;\n"
         << "\t\tcontent: '';\n"
         << "\t\tposition: absolute;\n"
         << "\t\twidth: 100%;\n"
         << "\t\theight: 100%;\n"
         << "\t\tbackground: #090345;\n"
         << "\t\tleft: 0;\n"
         << "\t\ttop: 0;\n"
         << "\t\tborder-radius: 10px;\n"
         << "\t}\n"
         << "\t.upload-button {\n"
         << "\t\tbackground-color: #8d0000;\n"
         << "\t\tcolor: #ffffff;\n"
         << "\t\tfont-weight: bold\n"
         << "\t}\n"
         << "\t.submit-button {\n"
         << "\t\tbackground-color: #8d0000;\n"
         << "\t\tcolor: #ffffff;\n"
         << "\t\tfont-weight: bold\n"
         << "\t}\n"
         << "\t</style>\n"
         << "</head>\n"
         << "<body>\n"
         << "\t<div class=\"container\">\n"
         << "\t\t<h1>Formulário POST</h1>\n"
         << "\t\t<a href=\"/\"><button class=\"buttons glow-on-hover\"><b>Home</b></button></a>\n"
         << "\t\t<form action=\"/post\" method=\"post\"><br>\n"
         << "\t\t\t<label for=\"key1\">Chave 1:</label>\n"
         << "\t\t\t<input type=\"text\" id=\"key1\" name=\"key1\"><br><br><br>\n"
         << "\t\t\t<label for=\"key2\">Chave 2:</label>\n"
         << "\t\t\t<input type=\"text\" id=\"key2\" name=\"key2\"><br><br><br>\n"
         << "\t\t\t<input type=\"submit\" value=\"Enviar\" class=\"buttons glow-on-hover submit-button\">\n"
         << "\t\t</form>\n"
         << "\t</div>\n"
         << "</body>\n"
         << "</html>";
    return html.str();
}


std::string ServerErrorHandler::generateUpload()
{
    std::ostringstream html;
    html << "<!DOCTYPE html>\n"
        << "<html lang=\"en\">\n"
        << "<head>\n"
        << "\t<meta charset=\"UTF-8\">\n"
        << "\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
        << "\t<title>File Upload</title>\n"
        << "\t<style>\n"
        << "\tbody {\n"
        << "\t\tfont-family: Arial, sans-serif;\n"
        << "\t\tdisplay: flex;\n"
        << "\t\tjustify-content: center;\n"
        << "\t\talign-items: center;\n"
        << "\t\theight: 70vh;\n"
        << "\t\tmargin: 0;\n"
        << "\t\tbackground-color: #01012b;\n"
        << "\t}\n"
        << "\t@keyframes pulse {\n"
        << "\t\t0% {\n"
        << "\t\t\ttransform: scale(1);\n"
        << "\t\t}\n"
        << "\t\t50% {\n"
        << "\t\t\ttransform: scale(1.1);\n"
        << "\t\t}\n"
        << "\t\t100% {\n"
        << "\t\t\ttransform: scale(1);\n"
        << "\t\t}\n"
        << "\t}\n"
        << "\th1 {\n"
        << "\t\tfont-family: \"Arial\", monospace;\n"
        << "\t\tfont-size: 2.5em;\n"
        << "\t\tfont-weight: 900;\n"
        // << "\t\tanimation: pulse 3s infinite;\n" // This line is commented out in the original HTML
        << "\t}\n"
        << "\t.container {\n"
        << "\t\ttext-align: center;\n"
        << "\t\tmax-width: 850px;\n"
        << "\t\twidth: 100%;\n"
        << "\t\tbackground-color: #94bbd0;\n"
        << "\t\tpadding: 20px;\n"
        << "\t\tborder-radius: 10px;\n"
        << "\t\tbox-shadow: 0px 0px 10px 0px rgba(0, 0, 0, 0.1);\n"
        << "\t}\n"
        << "\t.buttons {\n"
        << "\t\tfont-size: 20px;\n"
        // Background color and color are commented out in the original HTML
        << "\t\tpadding: 10px 20px;\n"
        << "\t\tborder: none;\n"
        << "\t\tborder-radius: 8px;\n"
        << "\t\tcursor: pointer;\n"
        << "\t\tmargin-bottom: 20px;\n"
        << "\t\tmargin-left: 10px;\n"
        << "\t\tmargin-top: 5px;\n"
        << "\t}\n"
        << "\t.credits_1 {\n"
        << "\t\ttext-align: center;\n"
        << "\t\tpadding: 15px;\n"
        << "\t\tbackground-color: #5f94c9;\n"
        << "\t\tmargin-top: 20px;\n"
        << "\t\tborder-radius: 10px;\n"
        << "\t}\n"
        << "\t.credits_2 {\n"
        << "\t\tmax-width: 850px;\n"
        << "\t\tmargin: auto;\n"
        << "\t}\n"
        << "\ta[href*=\"https://profile.intra.42.fr\"] {\n"
        << "\t\tcolor: rgb(7, 7, 114);\n"
        << "\t}\n"
        << "\ta[href*=\"https://profile.intra.42.fr\"]:hover {\n"
        << "\t\tcolor: rgb(255, 255, 255);\n"
        << "\t}\n"
        << "\ta[href*=\"https://github.com\"] {\n"
        << "\t\tcolor: rgb(7, 7, 114);\n"
        << "\t}\n"
        << "\ta[href*=\"https://github.com\"]:hover {\n"
        << "\t\tcolor: rgb(255, 255, 255);\n"
        << "\t}\n"
        << "\t.glow-on-hover {\n"
        << "\t\tborder: none;\n"
        << "\t\toutline: none;\n"
        << "\t\tcolor: #fff;\n"
        << "\t\tcursor: pointer;\n"
        << "\t\tposition: relative;\n"
        << "\t\tz-index: 0;\n"
        << "\t\tborder-radius: 10px;\n"
        << "\t}\n"
        << "\t.glow-on-hover:before {\n"
        << "\t\tcontent: '';\n"
        << "\t\tbackground: linear-gradient(45deg, #ff0000, #ff0000);\n"
        << "\t\tposition: absolute;\n"
        << "\t\ttop: -2px;\n"
        << "\t\tleft:-2px;\n"
        << "\t\tbackground-size: 400%;\n"
        << "\t\tz-index: -1;\n"
        << "\t\tfilter: blur(5px);\n"
        << "\t\twidth: calc(100% + 5px);\n"
        << "\t\theight: calc(100% + 5px);\n"
        << "\t\tanimation: glowing 20s linear infinite;\n"
        << "\t\topacity: 0;\n"
        << "\t\ttransition: opacity .3s ease-in-out;\n"
        << "\t\tborder-radius: 10px;\n"
        << "\t}\n"
        << "\t.glow-on-hover:active {\n"
        << "\t\tcolor: #000000\n"
        << "\t}\n"
        << "\t.glow-on-hover:active:after {\n"
        << "\t\tbackground: #72bae0;\n"
        << "\t}\n"
        << "\t.glow-on-hover:hover:before {\n"
        << "\t\topacity: 1;\n"
        << "\t}\n"
        << "\t.glow-on-hover:after {\n"
        << "\t\tz-index: -1;\n"
        << "\t\tcontent: '';\n"
        << "\t\tposition: absolute;\n"
        << "\t\twidth: 100%;\n"
        << "\t\theight: 100%;\n"
        << "\t\tbackground: #090345;\n"
        << "\t\tleft: 0;\n"
        << "\t\ttop: 0;\n"
        << "\t\tborder-radius: 10px;\n"
        << "\t}\n"
        << "\t.upload-button {\n"
        << "\t\tbackground-color: #0f5905;\n"
        << "\t\tcolor: #ffffff;\n"
        << "\t\tfont-weight: bold;\n"
        << "\t}\n"
        << "\t</style>\n"
        << "\t<link rel=\"icon\" type=\"image/vnd.microsoft.icon\" href=\"favicon.ico\" >\n"
        << "</head>\n"
        << "<body>\n"
        << "\t<div class=\"container\">\n"
        << "\t\t<h1>Upload a File</h1>\n"
        << "\t\t<a href=\"/\"><button class=\"buttons glow-on-hover\"><b>Home</b></button></a>\n"
        << "\t\t<form action=\"/cgi-bin/UploadScript.py/uploads\" method=\"post\" enctype=\"multipart/form-data\">\n"
        << "\t\t\t<input type=\"file\" name=\"file\" id=\"file\" class=\"buttons glow-on-hover\">\n"
        << "\t\t\t<input type=\"submit\" value=\"Upload\" class=\"buttons glow-on-hover upload-button\">\n"
        << "\t\t</form>\n"
        << "\t</div>\n"
        << "</body>\n"
        << "</html>";
    return html.str();
}